name: Wake Render Server

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 0-17 * * *"    
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Server
        run: |
          echo "Waking up server..."
          
          for i in {1..5}
          do
            echo "Attempt $i..."
            
            status=$(curl -o /dev/null -s -w "%{http_code}" -m 60 https://sale2service.onrender.com)
            
            if [ "$status" -eq 200 ]; then
              echo "✅ Server is awake!"
              exit 0
            else
              echo "⚠️ Failed with status $status. Retrying in 10s..."
              sleep 10
            fi
          done
          
          echo "❌ Server did not respond successfully"
          exit 1
